version: '3'

services:
  postgres:
    image: postgres
    restart: always
    container_name: art_capital_pg
    ports:
      - "5431:5432"
    volumes:
      - ./db/:/data/db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 7001:7001
    container_name: art_capital_user
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./.env


  